### PR TITLE
Sycl queue singleton

### PR DESCRIPTION
**Pull request by abagusetty**
1. Making sycl:;queue a singleton object, SYCL devices as sub-devices for Intel GPUs with multi-tiles
2. Removing un-needed memsets and wait() sync points except at one location in YAKL_parallel_for_c.h: https://github.com/abagusetty/YAKL/blob/sycl_queue_singleton/YAKL_parallel_for_c.h#L607

### CODE REVIEW

**Comment by abagusetty** [comment]
@mrnorman The tests pass except that there is this wait() for the kernel launch (https://github.com/abagusetty/YAKL/blob/sycl_queue_singleton/YAKL_parallel_for_c.h#L607). More surprisingly the fortran-side parallel_for_sycl() doesnt need the wait(), if we are indeed testing the usage.

**Comment by mrnorman** [comment]
Thanks for doing this! How do you feel about moving the `asyncHandler` definition and the `dev_mgr` class into the top of the YAKL.h file?

**Comment by abagusetty** [comment]
I did initially try to have the above SYCL class in YAKL.h but the YAKL_alloc_free.h (includes only YAKL_error.h) will not have the scope to access the contents of YAKL.h. Can you please confirm on this

**Comment by mrnorman** [comment]
Ahh, indeed. I had my reasons for having to segregate some of the files out, but I forget what they are at the moment or whether it's still necessary.

How about we create a new header file for the SYCL queue manager and asyncHandler and include it in both `YAKL.h` and `YAKL_alloc_free.h`?

**Comment by abagusetty** [comment]
That sounds good. Will do that

**Comment by abagusetty** [comment]
> That sounds good. Will do that

Done

**Comment by abagusetty** [comment]
Any leads on this one: The tests pass except that there is this wait() for the kernel launch (https://github.com/abagusetty/YAKL/blob/sycl_queue_singleton/YAKL_parallel_for_c.h#L607). More surprisingly the fortran-side parallel_for_sycl() doesnt need the wait(), if we are indeed testing the usage.

**Comment by abagusetty** [comment]
Fore record keeping:
```
abagusetty@iris18:/gpfs/jlse-fs0/projects/climate/abagusetty/E3SM_CRM_YAKL/YAKL/unit/build/machines/jlse$ ctest
Test project /gpfs/jlse-fs0/projects/climate/abagusetty/E3SM_CRM_YAKL/YAKL/unit/build/machines/jlse
      Start  1: CArray_test
 1/16 Test  #1: CArray_test ......................   Passed    3.40 sec
      Start  2: FArray_test
 2/16 Test  #2: FArray_test ......................   Passed    3.34 sec
      Start  3: Gator_test
 3/16 Test  #3: Gator_test .......................   Passed    0.04 sec
      Start  4: Random_test
 4/16 Test  #4: Random_test ......................   Passed    1.44 sec
      Start  5: FFT_test
 5/16 Test  #5: FFT_test .........................   Passed    0.88 sec
      Start  6: Reductions_test
 6/16 Test  #6: Reductions_test ..................   Passed    2.70 sec
      Start  7: Atomics_test
 7/16 Test  #7: Atomics_test .....................   Passed    1.62 sec
      Start  8: Pentadiagonal_test
 8/16 Test  #8: Pentadiagonal_test ...............   Passed    0.01 sec
      Start  9: Tridiagonal_test
 9/16 Test  #9: Tridiagonal_test .................   Passed    0.01 sec
      Start 10: Lambda_test
10/16 Test #10: Lambda_test ......................   Passed    1.10 sec
      Start 11: Fortran_Link_test
11/16 Test #11: Fortran_Link_test ................Subprocess aborted***Exception:   0.04 sec
      Start 12: Fortran_Gator_test
12/16 Test #12: Fortran_Gator_test ...............   Passed    0.03 sec
      Start 13: OpenMP_Regions_test
13/16 Test #13: OpenMP_Regions_test ..............   Passed    0.04 sec
      Start 14: Intrinsics_test
14/16 Test #14: Intrinsics_test ..................   Passed    1.58 sec
      Start 15: ParForC_test
15/16 Test #15: ParForC_test .....................   Passed    1.17 sec
      Start 16: ParForFortran_test
16/16 Test #16: ParForFortran_test ...............   Passed    1.13 sec

94% tests passed, 1 tests failed out of 16

Total Test time (real) =  18.63 sec

The following tests FAILED:
	 11 - Fortran_Link_test (Subprocess aborted)
Errors while running CTest
Output from these tests are in: /gpfs/jlse-fs0/projects/climate/abagusetty/E3SM_CRM_YAKL/YAKL/unit/build/machines/jlse/Testing/Temporary/LastTest.log
Use "--rerun-failed --output-on-failure" to re-run the failed cases verbosely.
```

**Comment by mrnorman** [comment]
Thanks for doing that. No leads on the C-style wait() except that if it occurs for one and not the other, it's possible the issue is only passing the C-style by luck. I will look more into it. Seems like the queue order isn't being respected in some part of the code for some reason.

**Comment by abagusetty** [comment]
I'll dig a bit deeper today. I agree that Fortran might got bit lucky. I am looking more into the `functorBuffer` usage for the temporary buffer that is being passed into the kernel launch, since the failing tests are using that section. 

On the other hand, if queue `in_order` property isn't working as expected, that would be a huge bug in llvm.

**Comment by mrnorman** [comment]
Btw, I like the Singleton implementation you created more than the pointer approach I did. Just to understand, though, would the pointer-based approach I tried earlier have avoided the static initialization order fiasco as well?

**Comment by mrnorman** [comment]
Regarding the `functorBuffer`, it's possible that the parallel_for is launching asynchronously but that in that asynchronous launch, it assumes that the functor is already present at that address and "preloads" it in prep for the kernel launch. And that in that preloading, we violate the queue order because it hasn't arrived yet. What do you think?

**Comment by abagusetty** [comment]
> Btw, I like the Singleton implementation you created more than the pointer approach I did. Just to understand, though, would the pointer-based approach I tried earlier have avoided the static initialization order fiasco as well?

"global pointer" would avoid the static initialization IMO. I just experimented singleton for the benefits of RAII, avoiding multiple declarations of the global variables in multiple files, etc. Also to avoid any doubt of this order of creation and destruction issue completely, just in case.

**Comment by abagusetty** [comment]
> Regarding the `functorBuffer`, it's possible that the parallel_for is launching asynchronously but that in that asynchronous launch, it assumes that the functor is already present at that address and "preloads" it in prep for the kernel launch. And that in that preloading, we violate the queue order because it hasn't arrived yet. What do you think?

The sycl queue is in-order (in other words: the tasks are executed in order they are enqueued). Mimicing cudaStream (FIFO). Given the same singleton queue being used (checked the address) at the `yakl::memset(test8d, 0)` and the `yakl::instance::sum(test8d != 0) die...` this should have made things in order and fence() is enforced anyway at the end of reduction intrinsic. 

regarding the "preload", I believe that the `functorBuffer` variable is already allocated with appropriate memory (in yakl::init() of YAKL_init.h). All we are doing is just taking that `void* functorBuffer` copying the contents of functor `(F const &f)` into it and passing that to the kernel launch. Do you think this is correct. Since the copy is launched before the kernel launch and also the same singleton queue being used. It should have been all good. 

also one question I had was how did the `functorBuffer` after the kernel sync the updated results to the functor `F const& f)

**Comment by mrnorman** [comment]
Thanks. I'm not sure I fully understood that last question.

**Comment by mrnorman** [comment]
From the Kokkos implementation, I saw this:
```C++
192 
193   // An indirect kernel is one where the functor to be executed is explicitly
194   // copied to USM memory before being executed, to get around the
195   // trivially copyable limitation of SYCL.
196   using IndirectKernelMem = USMObjectMem<sycl::usm::alloc::shared>;
197   IndirectKernelMem m_indirectKernelMem;
```

They're using USM, whereas, I don't think we are. I don't know if this makes a difference.

**Comment by mrnorman** [comment]
https://github.com/kokkos/kokkos/blob/master/core/src/SYCL/Kokkos_SYCL_Instance.cpp
https://github.com/kokkos/kokkos/blob/master/core/src/SYCL/Kokkos_SYCL_Instance.hpp

These are where kokkos handles functor copying and execution. I'll be looking into it in more detail later this week and next. A lot of it is abstracted, and it's taking a lot of time for me to figure out what's going on in the end.

**Comment by mrnorman** [comment]
The best I can tell so far, though, is that Kokkos uses `wait()` or `wait_and_throw()` after the functor copy `submit_barrier()` for the parallel_for event. So I think that maybe until the `SYCL_DEVICE_COPYABLE` is defined, we just need to add `.wait()`.

**Comment by abagusetty** [comment]
> 



> From the Kokkos implementation, I saw this:
> 
> ```c++
> 192 
> 193   // An indirect kernel is one where the functor to be executed is explicitly
> 194   // copied to USM memory before being executed, to get around the
> 195   // trivially copyable limitation of SYCL.
> 196   using IndirectKernelMem = USMObjectMem<sycl::usm::alloc::shared>;
> 197   IndirectKernelMem m_indirectKernelMem;
> ```
> 
> They're using USM, whereas, I don't think we are. I don't know if this makes a difference.

We too are using USM objects (aka pointers) during the allocation. That specific case of `using IndirectKernelMem = USMObjectMem<sycl::usm::alloc::shared>;` is an initialization which is causing problems in E3SM EKAT wrappers. I have been in touch to replace them to `alloc::device` `::shared` or `::device` might certainly not make an impact IMO to our issue.

**Comment by abagusetty** [comment]
Just verified, that replacing `malloc_device` with `malloc_shared` for the `functorBuffer` didnt really fix the issue. 

For the time being the above commit places a `.wait()` on the copy operation for both C and fortran style launches. All the appropriate test cases pass. This will ensure just the copy operation is completed. However kernel launch still stays async with respect to the host. We can revisit to remove the wait on the copy op. Thanks for the tip on `SYCL_DEVICE_COPYABLE`

**Comment by mrnorman** [comment]
The branch currently fails to compile with `source jlse_gpu_debug.sh`

**Comment by abagusetty** [comment]
> 

I can take a peek at it now

**Comment by mrnorman** [comment]
Thanks! When merged with master, I now get segfaults for many of the test cases with `jlse_gpu_debug.sh`. Here's a gdb-oneapi trace for CArray:

```bash
#22 0x0000000000538f9a in cl::sycl::queue::submit<cl::sycl::queue::parallel_for_impl<cl::sycl::detail::auto_name, yakl::c::parallel_for_sycl<yakl::memset<float, 1, 1, 1, float>(yakl::Array<float, 1, 1, 1>&, float)::{lambda(int)#1}, 1, true>(yakl::c::Bounds<1, true> const&, yakl::memset<float, 1, 1, 1, float>(yakl::Array<float, 1, 1, 1>&, float)::{lambda(int)#1} const&, int)::{lambda(cl::sycl::id<1>)#1}, 1>(cl::sycl::range<1>, yakl::c::parallel_for_sycl<yakl::memset<float, 1, 1, 1, float>(yakl::Array<float, 1, 1, 1>&, float)::{lambda(int)#1}, 1, true>(yakl::c::Bounds<1, true> const&, yakl::memset<float, 1, 1, 1, float>(yakl::Array<float, 1, 1, 1>&, float)::{lambda(int)#1} const&, int)::{lambda(cl::sycl::id<1>)#1}, cl::sycl::detail::code_location const&)::{lambda(cl::sycl::handler&)#1}> (this=0xd9d190, CGF=..., CodeLoc=...)
    at /soft/restricted/CNDA/sdk/2021.10.30.001/oneapi/compiler/pseudo-20211026/compiler/linux/bin/../include/sycl/CL/sycl/queue.hpp:274
#23 0x0000000000538f0f in cl::sycl::queue::parallel_for_impl<cl::sycl::detail::auto_name, yakl::c::parallel_for_sycl<yakl::memset<float, 1, 1, 1, float>(yakl::Array<float, 1, 1, 1>&, float)::{lambda(int)#1}, 1, true>(yakl::c::Bounds<1, true> const&, yakl::memset<float, 1, 1, 1, float>(yakl::Array<float, 1, 1, 1>&, float)::{lambda(int)#1} const&, int)::{lambda(cl::sycl::id<1>)#1}, 1>(cl::sycl::range<1>, yakl::c::parallel_for_sycl<yakl::memset<float, 1, 1, 1, float>(yakl::Array<float, 1, 1, 1>&, float)::{lambda(int)#1}, 1, true>(yakl::c::Bounds<1, true> const&, yakl::memset<float, 1, 1, 1, float>(yakl::Array<float, 1, 1, 1>&, float)::{lambda(int)#1} const&, int)::{lambda(cl::sycl::id<1>)#1}, cl::sycl::detail::code_location const&) (this=0xd9d190, NumWorkItems=cl::sycl::range<1> = {...}, KernelFunc=..., CodeLoc=...)
    at /soft/restricted/CNDA/sdk/2021.10.30.001/oneapi/compiler/pseudo-20211026/compiler/linux/bin/../include/sycl/CL/sycl/queue.hpp:1100
#24 0x0000000000538e5a in cl::sycl::queue::parallel_for<cl::sycl::detail::auto_name, yakl::c::parallel_for_sycl<yakl::memset<float, 1, 1, 1, float>(yakl::Array<float, 1, 1, 1>&, float)::{lambda(int)#1}, 1, true>(yakl::c::Bounds<1, true> const&, yakl::memset<float, 1, 1, 1, float>(yakl::Array<float, 1, 1, 1>&, float)::{lambda(int)#1} const&, int)::{lambda(cl::sycl::id<1>)#1}>(cl::sycl::range<1>, yakl::c::parallel_for_sycl<yakl::memset<float, 1, 1, 1, float>(yakl::Array<float, 1, 1, 1>&, float)::{lambda(int)#1}, 1, true>(yakl::c::Bounds<1, true> const&, yakl::memset<float, 1, 1, 1, float>(yakl::Array<float, 1, 1, 1>&, float)::{lambda(int)#1} const&, int)::{lambda(cl::sycl::id<1>)#1} const&, cl::sycl::detail::code_location const&) (this=0xd9d190, NumWorkItems=cl::sycl::range<1> = {...}, KernelFunc=..., CodeLoc=...)
    at /soft/restricted/CNDA/sdk/2021.10.30.001/oneapi/compiler/pseudo-20211026/compiler/linux/bin/../include/sycl/CL/sycl/queue.hpp:736
#25 0x0000000000538da3 in yakl::c::parallel_for_sycl<yakl::memset<float, 1, 1, 1, float>(yakl::Array<float, 1, 1, 1>&, float)::{lambda(int)#1}, 1, true>(yakl::c::Bounds<1, true> const&, yakl::memset<float, 1, 1, 1, float>(yakl::Array<float, 1, 1, 1>&, float)::{lambda(int)#1} const&, int) (bounds=..., f=..., vectorSize=128) at /home/ac.normanmr/YAKL/YAKL_parallel_for_c.h:605
#26 0x0000000000538c73 in yakl::c::parallel_for<yakl::memset<float, 1, 1, 1, float>(yakl::Array<float, 1, 1, 1>&, float)::{lambda(int)#1}, 1, true>(yakl::c::Bounds<1, true> const&, yakl::memset<float, 1, 1, 1, float>(yakl::Array<float, 1, 1, 1>&, float)::{lambda(int)#1} const&, int) (bounds=..., f=..., vectorSize=128) at /home/ac.normanmr/YAKL/YAKL_parallel_for_c.h:886
#27 0x0000000000538bbc in yakl::c::parallel_for<yakl::memset<float, 1, 1, 1, float>(yakl::Array<float, 1, 1, 1>&, float)::{lambda(int)#1}>(yakl::c::LBnd, yakl::memset<float, 1, 1, 1, float>(yakl::Array<float, 1, 1, 1>&, float)::{lam--Type <RET> for more, q to quit, c to continue without paging--
bda(int)#1} const&, int) (bnd=..., f=..., vectorSize=128) at /home/ac.normanmr/YAKL/YAKL_parallel_for_c.h:920
#28 0x0000000000520440 in yakl::memset<float, 1, 1, 1, float> (arr=..., val=0) at /home/ac.normanmr/YAKL/YAKL.h:187
#29 0x00000000004d466d in main () at /home/ac.normanmr/YAKL/unit/CArray/CArray.cpp:65
```

This is with the iris queue on jlse

**Comment by mrnorman** [comment]
I merged everything in here into master except memset for SYCL, which did not pass unit tests.

The following issues still remain: https://github.com/mrnorman/YAKL/issues/44

**Pull request closed without merging**
