### PR TITLE
Enabling multiple YAKLs per Exe / CMake build with different hardware targets

### PR DESCRIPTION
**Pull request by mrnorman**
### Ensures unique CMake target names
* If the user defines the CMake variable `YAKL_TARGET_SUFFIX`, this will be appended to the YAKL target name and will create a namespace with a unique and unrelated name to wrap around every `namespace yakl { ... }`
   * If the user does not define this CMake variable, then nothing is appended to the YAKL target names, and no namespace is wrapped around `namespace yakl { ... }`.
   * There are no requirements on the `YAKL_TARGET_SUFFIX` provided by the user. It can pretty much be anything. A randomly generated unique namespace is used, so it won't clash with anything.
* **Splitting YAKL into two libraries**: a header-only C++ library with the default CMake target name of `yakl`, and a Fortran interface library with compiled sources with the default CMake target name of `yakl_fortran_interfaces`.
* The CMake variables `YAKL_TARGET` and `YAKL_FORTRAN_INTERFACES_TARGET` are defined in parent scope so the caller knows what the target names are more conveniently (even though it's easy to create anyway).
* Adding both targets to the install code, using `YAKL_TARGET` as the namespace
* For all source files, adding `__YAKL_NAMESPACE__WRAPPER_BEGIN__` before `namespace yakl {`, and adding `__YAKL_NAMESPACE_WRAPPER_END__` after the closing bracket of `namespace yakl {`. 
   * If the user specified the CMake variable `YAKL_TARGET_SUFFIX`, these CMake macros add a namespace of a randomly generated and unique name around `namespace yakl {` to avoid conflicting object files and to make it clear how to use a given yakl build.
   * If the user doesn't specify that CMake variable, these CMake macros do nothing
   * At the top of `YAKL.h`, the behavior of unnamed namespaces is emulated with `namespace RANDOMLY_GENERATED {}; using namespace RANDOMLY_GENERATED;` so that the user has access to the yakl namespace like normal with no change in how it's used (even though it is guaranteed uniqueness now during linking).
* Moving definitions to `yakl_utils.cmake` so that they are used for all projects that use `yakl_process_target` or `yakl_process_cxx_source_files`.

### Example: `set(YAKL_TARGET_SUFFIX "e3sm_omega")`
* The YAKL target is `yakl_e3sm_omega`, and the fortran interfaces target is `yakl_fortran_interfaces_e3sm_omega`
* The Fortran module to control this YAKL instance is `gator_mod_e3sm_omega`, and the module file is called `gator_mod_e3sm_omega.mod`.

### CODE REVIEW

**Comment by mrnorman** [comment]
@sarats , @abagusetty , @xyuan , I'd like to hear your thoughts on this before I merge. The time is likely coming very soon where we'll need to support multiple YAKLs in the same executable and CMake build. This can be required due to different optimization levels, different backend targets, and other reasons. This PR will enable multiple YAKLs while avoiding clashing of CMake target names and object file symbol names.

@pkestene , I'd like to know if this maintains expected behavior for your install use case.

**Comment by mrnorman** [comment]
### TODO: I'm going to switch to using CMake's string generation `UUID` to create the namespace name. This way, the user can append whatever suffix they want without worrying that it might be clashing with another namespace.

**Comment by xyuan** [comment]
This is nice feature to have it in YAKL, it makes the configurations simple to handle, thanks @mrnorman to consider it.

**Comment by sarats** [comment]
Macros to the rescue! No fancy new language feature to make this work, so don't have to worry about some compiler barfing.
I like it.

**Pull request merged**
